<a href="https://colab.research.google.com/github/KKeun-B/learning/blob/main/2020/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

* Python을 활용한 수치연산을 위한 라이브러리
 * Python에서 Numpy를 잘 활용하면 Matlab과 유사하게 사용할 수 있음.

In [1]:
import numpy as np
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

##Numpy Array 기본

* Array 선언 방법 예시

In [2]:
import numpy as np
np.random.seed(4452)  # 재현성을 위한 랜덤 시드 설정

x1 = np.random.randint(10, size=6)  # 1차원 Array
x2 = np.random.randint(10, size=(3, 4))  # 2차원 Array
x3 = np.random.randint(10, size=(3, 4, 5))  # 3차원 Array

 * Python list와는 다르게 numpy array 내부의 데이터 형은 전부 동일함

In [3]:
np.array([3.14, 4, 2, 4])

array([3.14, 4.  , 2.  , 4.  ])

 * numpy array는 데이터의 형태를 명시적으로 지정할 수 있음

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

 * numpy array는 명시적으로 다차원 데이터를 보관할 수 있음

In [5]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

  * Numpy array 생성 방법
 

In [6]:
# 0으로 가득 찬 길이가 10인 정수 array 생성
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# 1로 찬 3x5 실수 array 생성
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# 3.14로 찬 3x5 array 생성
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# array를 규칙에 맞춰서 생성
# 0으로 시작해서 2 간격으로 20까지 (20 미포함)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# 0에서 1사이에 균등하게 5개의 원소를 가진 array 생성
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# 0에서 1 사이의 값을 랜덤하게 사용하여 3x3 array 생성
np.random.random((3,3))

array([[0.77605415, 0.41920557, 0.63066741],
       [0.27947124, 0.52158297, 0.71498491],
       [0.99910395, 0.63741838, 0.20788391]])

In [12]:
# 평균이 0이고 분산이 1인 분포에서 랜덤하게 값을 추출하여 3x3 array 생성
np.random.normal(0, 1, (3, 3))

array([[ 0.31382095,  0.28251813, -0.36747149],
       [ 1.04280907, -0.3391419 ,  0.88315767],
       [ 0.29107616, -0.73378086,  1.03497911]])

In [13]:
# [0. 10) 사이에서 랜덤하게 정수를 추출하여 3x3 array 생성
np.random.randint(0, 10, (3, 3))

array([[0, 6, 7],
       [8, 8, 3],
       [1, 4, 8]])

In [14]:
# 3x3 identity 행렬 생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 * Numpy Data Types
  * bool_: Boolean (True or False) stored as a byte
  * int_: Default integer type (same as C long; normally either int64 or int32)
  * intc: Identical to C int (normally int32 or int64)
  * intp: Integer used for indexing (same as C ssize_t; normally either int32 or int64)
  * int8: Byte (-128 to 127)
  * int16: Integer (-32768 to 32767)
  * int32: Integer (-2147483648 to 2147483647)
  * int64: Integer (-9223372036854775808 to 9223372036854775807)
  * uint8: Unsigned integer (0 to 255)
  * uint16: Unsigned integer (0 to 65535)
  * uint32: Unsigned integer (0 to 4294967295)
  * uint64: Unsigned integer (0 to 18446744073709551615)
  * float_: Shorthand for float64.
  * float16: Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
  * float32: Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
  * float64: Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
  * complex_: Shorthand for complex128.
  * complex64: Complex number, represented by two 32-bit floats
  * complex128: Complex number, represented by two 64-bit floats

* Array의 내부 변수 및 의미

In [15]:
x3 = np.random.randint(10, size=(3, 4, 5))  # 3차원 Array
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


## Array Index

In [16]:
import numpy as np
np.random.seed(4452)  # 재현성을 위한 랜덤 시드 설정

x1 = np.random.randint(10, size=6)  # 1차원 Array
x2 = np.random.randint(10, size=(3, 4))  # 2차원 Array
x3 = np.random.randint(10, size=(3, 4, 5))  # 3차원 Array

In [17]:
print(x1)

[1 6 3 7 3 1]


In [18]:
x1[0]

1

In [19]:
x1[4]

3

In [20]:
x1[-1]

1

In [21]:
x2

array([[8, 7, 4, 8],
       [5, 9, 3, 7],
       [3, 5, 2, 7]])

In [24]:
x2[0,0]

8

In [23]:
x2[2]

array([3, 5, 2, 7])

In [25]:
x2[2,0]

3

In [26]:
x2[2,-1]

7

In [27]:
x2[0,0]=12
x2

array([[12,  7,  4,  8],
       [ 5,  9,  3,  7],
       [ 3,  5,  2,  7]])

In [28]:
x2[0,0]=3.14159
x2

array([[3, 7, 4, 8],
       [5, 9, 3, 7],
       [3, 5, 2, 7]])

## Array Slice (1)


* x[시작:끝:간격]
* 1차원인 경우 아래와 같음

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[:5]

array([0, 1, 2, 3, 4])

In [31]:
x[5:]

array([5, 6, 7, 8, 9])

In [32]:
x[4:7]

array([4, 5, 6])

In [33]:
x[::2]

array([0, 2, 4, 6, 8])

In [34]:
x[1::2]

array([1, 3, 5, 7, 9])

In [35]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x[5::-2]

array([5, 3, 1])

## Array Slice (2)

* 다차원인 경우 아래와 같음

In [37]:
x2

array([[3, 7, 4, 8],
       [5, 9, 3, 7],
       [3, 5, 2, 7]])

In [38]:
x2[:2,:3]

array([[3, 7, 4],
       [5, 9, 3]])

In [39]:
x2[:3,::2]

array([[3, 4],
       [5, 3],
       [3, 2]])

In [40]:
x2[::-1,::-1]

array([[7, 2, 5, 3],
       [7, 3, 9, 5],
       [8, 4, 7, 3]])


## Array Slice (3)

* 특정 열 혹은 행 값 접근

In [41]:
x2[:,0]

array([3, 5, 3])

In [42]:
x2[0,:]

array([3, 7, 4, 8])

In [43]:
x2[0]

array([3, 7, 4, 8])

# Numpy Array 연산

## 반복문 속도

* Python의 기본 연산은 느리게 작동함
* C언어에서와 같이 반복문을 작성할 수는 있으나, 그 경우 연산 속도가 느림

In [44]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

* ```%timeit```을 통해 연산시간을 특정할 수 있음



In [45]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 5: 2.19 s per loop


## UFuncs

* Numpy에서는 Vectorized operation을 지원함

In [46]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [47]:
%timeit (1.0 / big_array)

100 loops, best of 5: 2.03 ms per loop


In [48]:
x1 = np.arange(5) 
x2 = np.arange(1, 6)
x3 = x1 / x2
print(x1)
print(x2)
print(x3)

[0 1 2 3 4]
[1 2 3 4 5]
[0.         0.5        0.66666667 0.75       0.8       ]


In [49]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

* Array 대수 연산

In [50]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [51]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [52]:
np.add(x, 2)

array([2, 3, 4, 5])

* **Operator Equivalent ufunc**
 * ''' + '''	np.add	Addition (e.g., 1 + 1 = 2)
 * ''' - '''	np.subtract	Subtraction (e.g., 3 - 2 = 1)
 * ''' - '''	np.negative	Unary negation (e.g., -2)
 * ''' * '''	np.multiply	Multiplication (e.g., 2 * 3 = 6)
 * ''' / '''	np.divide	Division (e.g., 3 / 2 = 1.5)
 * ''' // '''	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
 * ''' ** '''	np.power	Exponentiation (e.g., 2 ** 3 = 8)
 * ''' % '''	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)

* 절댓값

In [53]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [54]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [55]:
np.abs(x)

array([2, 1, 0, 1, 2])

* 삼각함수

In [56]:
theta = np.linspace(0, np.pi, 3)

In [57]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


* 지수함수와 로그

In [58]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [59]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [60]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


# 기타 참고 자료
* https://jakevdp.github.io/PythonDataScienceHandbook/index.html